# Generated by Django 5.2.4 on 2025-07-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_iotdata_brightnesspercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdata',
            name='detected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
